# Generated by Django 5.0.4 on 2024-05-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipee_name',
            new_name='receipe_name',
        ),
    ]
